[profile.default]
solc = '0.8.19'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
fuzz_runs = 1000
optimizer_runs = 10_000
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.fuzz]
max_test_rejects = 655360
